// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGa4lAmITF9Z3XN-gaml-RLYegqLIPkEg',
    appId: '1:733458642382:web:2704219ddaf4cc0865e79f',
    messagingSenderId: '733458642382',
    projectId: 'family-badgets',
    authDomain: 'family-badgets.firebaseapp.com',
    storageBucket: 'family-badgets.firebasestorage.app',
    measurementId: 'G-LXFMNCR9M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZjGayP2eFzvwq6pW0hVHKeMVcP1d9Vs',
    appId: '1:733458642382:android:242d9cecef8d27df65e79f',
    messagingSenderId: '733458642382',
    projectId: 'family-badgets',
    storageBucket: 'family-badgets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqdvGMvis6ZmrOGRwFzscAZV_9_RKRw8',
    appId: '1:733458642382:ios:eef0bf278306081765e79f',
    messagingSenderId: '733458642382',
    projectId: 'family-badgets',
    storageBucket: 'family-badgets.firebasestorage.app',
    iosBundleId: 'com.example.familyBudgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqdvGMvis6ZmrOGRwFzscAZV_9_RKRw8',
    appId: '1:733458642382:ios:eef0bf278306081765e79f',
    messagingSenderId: '733458642382',
    projectId: 'family-badgets',
    storageBucket: 'family-badgets.firebasestorage.app',
    iosBundleId: 'com.example.familyBudgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGa4lAmITF9Z3XN-gaml-RLYegqLIPkEg',
    appId: '1:733458642382:web:992e12335fbc9fa365e79f',
    messagingSenderId: '733458642382',
    projectId: 'family-badgets',
    authDomain: 'family-badgets.firebaseapp.com',
    storageBucket: 'family-badgets.firebasestorage.app',
    measurementId: 'G-ZQWZG24B30',
  );
}
